
language: csharp

os: linux
dist: trusty
group: edge
sudo: required
mono:
  - latest

services:
  - docker

script:
  - ./build.sh

deploy:
  provider: script
  script:
    - ./build.sh -t Publish
  on:
    branch: master
