
language: csharp

os: linux # Ubuntu 14.04
dist: trusty
group: edge
sudo: required
dotnet: 2.0.0
mono: none

services:
  - docker

script:
  - ./build.sh

deploy:
  provider: script
  script:
    - ./build.sh -t Publish
  on:
    branch: master
